### PR TITLE
Added Dropbox support

### PR DESCRIPTION
**Pull request by gamer4life1**
I forked this off your repo and #8.

### CODE REVIEW

**Comment by gamer4life1** [comment]
Thank you @jdtzmn fir the idea!

**Comment by gamer4life1** [comment]
Sorry, for the idea.

**Comment by jkutner** [comment]
@gamer4life1 thanks for working on this. If we merge this, however, it's likely that I won't be able to keep things up to date and working (I'm not familiar with craftbukkit). Maybe the best thing is to maintain your fork with Dropbox and craftbukkit, and then link to it in the docs/README of this repo. 

I honest think the Dropbox way is better if it works, so I'm happy to encourage folks to use that. It also sounds like you've got plugins working better.

What do you think?

**Comment by gamer4life1** [comment]
Ok, that sounds good.

**Comment by gamer4life1** [comment]
Should I make another or for the Readme?

**Comment by jkutner** [comment]
@gamer4life1 yea, that would be great. You can put something towards the top that says "for dropbox and plugin support..." or whatever. I might cherry-pick some things out of this PR later on.

**Pull request closed without merging**
