### PR TITLE
Dropbox sync support

### PR DESCRIPTION
**Pull request by sahlamba**
I took a shot at adding support for syncing to Dropbox.

### CODE REVIEW

**Comment by jkutner** [comment]
@sahlamba I'm hesitant to add Dropbox support because I won't be able to ensure it keeps working (I won't use it myself). I'm definitely not going to replace the S3 support fwiw.

You might also look at https://github.com/gamer4life1/minecraftBuildpack, which supports Dropbox.

**Comment by jkutner** [comment]
Ignore my comment about "replace the S3 support". I read your README changes incorrectly.

**Comment by sahlamba** [comment]
@jkutner Thanks for the response, I didn't use https://github.com/gamer4life1/minecraftBuildpack because I felt it had a lot of unnecessary changes from the base buildpack. Also, it uses a legacy approach of using the Dropbox API, my README changes show the new way of working with Dropbox APIs using app scopes so it should work for a long time IMO.

I feel adding Dropbox support will immensely increase the usability of the buildpack, since it's easier (and free) to set up compared to S3. Let me know your final thoughts on this, feel free to close the PR if you think it would be too much overhead.

**Comment by jkutner** [comment]
@sahlamba ok, thanks for the info. I'll give a test (probably within the next week), and see what I think.

Are you willing to maintain the Dropbox support? Will you be willing answer questions on Github issues, and review PRs?

**Comment by sahlamba** [comment]
@jkutner I would be happy to maintain Dropbox support and answer queries/review PRs on it. Thanks! 

Let me know how your testing goes and if I can improve anything (implementation/docs/etc).

**Comment by GustavoCinque** [comment]
Any news on this PR @jkutner?

**Comment by sahlamba** [comment]
Closing due to inactivity. Please feel free to reopen if required. Thanks!

**Pull request closed without merging**
